build: 
  ldflags: -s -w -X main.Version={{.Version}}
  binary: trawl
  env: 
    - CGO_ENABLED=0 
  goos: 
    - linux
    - darwin
  goarch: 
    - amd64
archive:
  format: tar.gz
snapshot: 
  name_template: "{{.Commit}}"
fpm:
  vendor: Rob Phoenix
  homepage: https://github.com/robphoenix/trawl
  maintainer: Rob Phoenix
  description: A strong fishing net for dragging along the sea bottom to collect IP addresses and similar flotsam & jetsam
  formats:
    - deb
  bindir: /usr/local/bin
